test_wav_play = executable(
  'test_wav_play',
  'wav_play.cpp',
  dependencies : [engine_dep],
)

test_play_each_format = executable(
  'test_play_each_format',
  'play_each_format.cpp',
  dependencies : [engine_dep],
)

test_engine_play = executable(
  'test_engine_play',
  'engine_play.cpp',
  dependencies : [engine_dep],
)

test_device_list = executable(
  'test_device_list',
  'device_list.cpp',
  dependencies : [engine_dep],
)

test_telemetry_dump = executable(
  'test_telemetry_dump',
  'telemetry_dump.cpp',
  dependencies : [engine_dep],
)
